// this file created by hashmapCreator.js

export const countriesHashmap = {
	Afghanistan: 0,
	Albania: 1,
	Algeria: 2,
	Andorra: 3,
	Angola: 4,
	"Antigua and Barbuda": 5,
	Argentina: 6,
	Armenia: 7,
	Australia: 8,
	Austria: 9,
	Azerbaijan: 10,
	Bahamas: 11,
	Bahrain: 12,
	Bangladesh: 13,
	Barbados: 14,
	Belarus: 15,
	Belgium: 16,
	Belize: 17,
	Benin: 18,
	Bhutan: 19,
	Bolivia: 20,
	"Bosnia and Herzegovina": 21,
	Botswana: 22,
	Brazil: 23,
	Brunei: 24,
	Bulgaria: 25,
	"Burkina Faso": 26,
	Burma: 27,
	Burundi: 28,
	"Cabo Verde": 29,
	Cambodia: 30,
	Cameroon: 31,
	Canada: 32,
	"Central African Republic": 33,
	Chad: 34,
	Chile: 35,
	China: 36,
	Colombia: 37,
	Comoros: 38,
	"Congo (Brazzaville)": 39,
	"Congo (Kinshasa)": 40,
	"Costa Rica": 41,
	"Cote d'Ivoire": 42,
	Croatia: 43,
	Cuba: 44,
	Cyprus: 45,
	Czechia: 46,
	Denmark: 47,
	"Diamond Princess": 48,
	Djibouti: 49,
	Dominica: 50,
	"Dominican Republic": 51,
	Ecuador: 52,
	Egypt: 53,
	"El Salvador": 54,
	"Equatorial Guinea": 55,
	Eritrea: 56,
	Estonia: 57,
	Eswatini: 58,
	Ethiopia: 59,
	Fiji: 60,
	Finland: 61,
	France: 62,
	Gabon: 63,
	Gambia: 64,
	Georgia: 65,
	Germany: 66,
	Ghana: 67,
	Greece: 68,
	Grenada: 69,
	Guatemala: 70,
	Guinea: 71,
	"Guinea-Bissau": 72,
	Guyana: 73,
	Haiti: 74,
	"Holy See": 75,
	Honduras: 76,
	Hungary: 77,
	Iceland: 78,
	India: 79,
	Indonesia: 80,
	Iran: 81,
	Iraq: 82,
	Ireland: 83,
	Israel: 84,
	Italy: 85,
	Jamaica: 86,
	Japan: 87,
	Jordan: 88,
	Kazakhstan: 89,
	Kenya: 90,
	"Korea, South": 91,
	Kosovo: 92,
	Kuwait: 93,
	Kyrgyzstan: 94,
	Laos: 95,
	Latvia: 96,
	Lebanon: 97,
	Lesotho: 98,
	Liberia: 99,
	Libya: 100,
	Liechtenstein: 101,
	Lithuania: 102,
	Luxembourg: 103,
	"MS Zaandam": 104,
	Madagascar: 105,
	Malawi: 106,
	Malaysia: 107,
	Maldives: 108,
	Mali: 109,
	Malta: 110,
	"Marshall Islands": 111,
	Mauritania: 112,
	Mauritius: 113,
	Mexico: 114,
	Moldova: 115,
	Monaco: 116,
	Mongolia: 117,
	Montenegro: 118,
	Morocco: 119,
	Mozambique: 120,
	Namibia: 121,
	Nepal: 122,
	Netherlands: 123,
	"New Zealand": 124,
	Nicaragua: 125,
	Niger: 126,
	Nigeria: 127,
	"North Macedonia": 128,
	Norway: 129,
	Oman: 130,
	Pakistan: 131,
	Panama: 132,
	"Papua New Guinea": 133,
	Paraguay: 134,
	Peru: 135,
	Philippines: 136,
	Poland: 137,
	Portugal: 138,
	Qatar: 139,
	Romania: 140,
	Russia: 141,
	Rwanda: 142,
	"Saint Kitts and Nevis": 143,
	"Saint Lucia": 144,
	"Saint Vincent and the Grenadines": 145,
	"San Marino": 146,
	"Sao Tome and Principe": 147,
	"Saudi Arabia": 148,
	Senegal: 149,
	Serbia: 150,
	Seychelles: 151,
	"Sierra Leone": 152,
	Singapore: 153,
	Slovakia: 154,
	Slovenia: 155,
	"Solomon Islands": 156,
	Somalia: 157,
	"South Africa": 158,
	"South Sudan": 159,
	Spain: 160,
	"Sri Lanka": 161,
	Sudan: 162,
	Suriname: 163,
	Sweden: 164,
	Switzerland: 165,
	Syria: 166,
	"Taiwan*": 167,
	Tajikistan: 168,
	Tanzania: 169,
	Thailand: 170,
	"Timor-Leste": 171,
	Togo: 172,
	"Trinidad and Tobago": 173,
	Tunisia: 174,
	Turkey: 175,
	US: 176,
	Uganda: 177,
	Ukraine: 178,
	"United Arab Emirates": 179,
	"United Kingdom": 180,
	Uruguay: 181,
	Uzbekistan: 182,
	Vanuatu: 183,
	Venezuela: 184,
	Vietnam: 185,
	"West Bank and Gaza": 186,
	"Western Sahara": 187,
	Yemen: 188,
	Zambia: 189,
	Zimbabwe: 190,
};

export const countries = [
	{
		country: "Afghanistan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Albania", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Algeria", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Andorra", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Angola", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Antigua and Barbuda",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Argentina",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Armenia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Australia",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Austria", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Azerbaijan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Bahamas", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Bahrain", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Bangladesh",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Barbados", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Belarus", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Belgium", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Belize", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Benin", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Bhutan", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Bolivia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Bosnia and Herzegovina",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Botswana", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Brazil", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Brunei", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Bulgaria", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Burkina Faso",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Burma", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Burundi", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Cabo Verde",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Cambodia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Cameroon", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Canada", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Central African Republic",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Chad", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Chile", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "China", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Colombia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Comoros", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Congo (Brazzaville)",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Congo (Kinshasa)",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Costa Rica",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Cote d'Ivoire",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Croatia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Cuba", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Cyprus", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Czechia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Denmark", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Diamond Princess",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Djibouti", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Dominica", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Dominican Republic",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Ecuador", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Egypt", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "El Salvador",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Equatorial Guinea",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Eritrea", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Estonia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Eswatini", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Ethiopia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Fiji", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Finland", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "France", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Gabon", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Gambia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Georgia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Germany", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Ghana", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Greece", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Grenada", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Guatemala",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Guinea", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Guinea-Bissau",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Guyana", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Haiti", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Holy See", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Honduras", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Hungary", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Iceland", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "India", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Indonesia",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Iran", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Iraq", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Ireland", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Israel", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Italy", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Jamaica", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Japan", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Jordan", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Kazakhstan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Kenya", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Korea, South",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Kosovo", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Kuwait", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Kyrgyzstan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Laos", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Latvia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Lebanon", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Lesotho", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Liberia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Libya", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Liechtenstein",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Lithuania",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Luxembourg",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "MS Zaandam",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Madagascar",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Malawi", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Malaysia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Maldives", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Mali", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Malta", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Marshall Islands",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Mauritania",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Mauritius",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Mexico", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Moldova", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Monaco", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Mongolia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Montenegro",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Morocco", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Mozambique",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Namibia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Nepal", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Netherlands",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "New Zealand",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Nicaragua",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Niger", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Nigeria", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "North Macedonia",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Norway", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Oman", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Pakistan", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Panama", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Papua New Guinea",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Paraguay", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Peru", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Philippines",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Poland", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Portugal", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Qatar", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Romania", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Russia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Rwanda", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Saint Kitts and Nevis",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Saint Lucia",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Saint Vincent and the Grenadines",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "San Marino",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Sao Tome and Principe",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Saudi Arabia",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Senegal", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Serbia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Seychelles",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Sierra Leone",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Singapore",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Slovakia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Slovenia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Solomon Islands",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Somalia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "South Africa",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "South Sudan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Spain", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Sri Lanka",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Sudan", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Suriname", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Sweden", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Switzerland",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Syria", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Taiwan*", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Tajikistan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Tanzania", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Thailand", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Timor-Leste",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Togo", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Trinidad and Tobago",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Tunisia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Turkey", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "US", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Uganda", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Ukraine", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "United Arab Emirates",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "United Kingdom",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Uruguay", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Uzbekistan",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Vanuatu", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "Venezuela",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Vietnam", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{
		country: "West Bank and Gaza",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{
		country: "Western Sahara",
		confirmedCount: 0,
		deathsCount: 0,
		recoveredCount: 0,
	},
	{ country: "Yemen", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Zambia", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
	{ country: "Zimbabwe", confirmedCount: 0, deathsCount: 0, recoveredCount: 0 },
];
